version: '2.1'

services:
  localstack:
    privileged: true
    image: localstack/localstack:0.10.1.2
    ports:
      - '4567-4585:4567-4585'
      - '4590-4593:4590-4593'
      - '8055:8080'
    environment:
      - DEFAULT_REGION=eu-central-1
      - SERVICES=s3
      - DEBUG="1"
      # - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker-reuse
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"