name: 'APISubjectPublisher'
description: 'Publishes the existing JSON schemas to Ceph'
inputs:
  subjects-path:  
    description: 'Repository root path where the subject json schemas are stored'
    required: false
    default: './dataext'
  environment:
    description: 'Environment id where the schema is deployed'
    required: true
  owner:
    description: 'Repository identifier running the action'
    reuired: false,
    default: '${{ github.repository }}'
  force:
    description: 'Flag that indicates that the subject will be overriden even when this repositority is not the owner.'
    required: false,
    default: 'false'
  tenant:
    description: 'Tenant for which the schemas will be deployed'
    required: true
  local-access-key:
    description: 'Ceph access key for the local environment'
    required: false
    default: 'any-access-token'
  local-secret-key:
    description: 'Ceph secret key for the local environment'
    required: true
    default: 'any-secret-token'
  des-access-key:
    description: 'Ceph access key for the dev environment'
    required: true
  des-secret-key:
    description: 'Ceph secret key for the dev environment'
    required: true
  preint-access-key:
    description: 'Ceph access key for the preint environment'
    required: true
  preint-secret-key:
    description: 'Ceph secret key for the preint environment'
    required: true
  pre-access-key:
    description: 'Ceph access key for the pre environment'
    required: true
  pre-secret-key:
    description: 'Ceph secret key for the pre environment'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'