name: "package-actions"
on:
  push:
    branches:
      - main
      - develop
      - 'v*'

jobs:
  build:
    env:
      PACKED_JS_PATH: 'packages/*/dist/'
      RELEASE_BRANCH: 'release/package-js-actions-${{ github.run_number }}'
      WORKING_DIR: '.'
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        id: extractBranch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install root dependencies
        run: npm install
      - name: Install action dependencies
        run: npx lerna bootstrap
      - name: Build all actions
        run: npx lerna run build

      - name: Check packed js changes
        id: packedJsStatus
        run: echo ::set-output name=changes::$(git status ${{ env.PACKED_JS_PATH }} --porcelain)
      - name: Commit packed js
        working-directory: ${{ env.WORKING_DIR }}
        id: commitPackedJs
        if: steps.packedJsStatus.outputs.changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b ${{ env.RELEASE_BRANCH }}
          git add ${{ env.PACKED_JS_PATH }}
          git commit -m "Pack openplatform actions with dependencies"
      - name: Push packed js
        if: steps.commitPackedJs.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          branch: ${{ env.RELEASE_BRANCH }}
      - name: Open Pull Request with packed JSs
        if: steps.commitPackedJs.outcome == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          created_pr=$(gh pr create --base ${{ steps.extractBranch.outputs.branch }} --head ${{ env.RELEASE_BRANCH }} --title "Packed JSs from build ${{ github.run_number }}" --body "PR created automatically from job ${{ github.run_number }}")
          sleep 5 # yay!
          gh pr merge ${create_pr} --merge