name: "package-actions"
on:
  push:
    branches:
      - main
      - develop
      - 'v*'

jobs:
  build:
    env:
      PACKED_JS_PATH: 'packages/*/dist/'
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        id: extractBranch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install root dependencies
        run: npm install
      - name: Install action dependencies
        run: npx lerna bootstrap
      - name: Build all actions
        run: npx lerna run build

      - name: Check packed js changes
        id: packedJsStatus
        run: echo ::set-output name=changes::$(git status ${{ env.PACKED_JS_PATH }} --porcelain)
      - name: Commit packed js
        id: commitPackedJs
        if: steps.packedJsStatus.outputs.changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b release/package-js-actions-${{ github.run_id }}
          git add ${{ env.PACKED_JS_PATH }}
          git commit -m "Pack openplatform actions with dependencies"
      - name: Push packed js
        if: steps.commitPackedJs.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          branch: release/package-js-actions-${{ github.run_id }}
      - name: Open Pull Request with packed JSs
        if: steps.commitPackedJs.outcome == 'success'
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          echo "mytoken $GITHUB_TOKEN"
          gh pr create --base ${{ steps.extractBranch.outputs.branch }} --head release/package-js-actions-${{ github.run_id }} --title "Packed JSs from build ${{ github.run_id }}" --body "PR created automatically from job ${{ github.run_id }}" 