name: "test-workflow"
on: 
  workflow_dispatch:
    inputs:
      tenant:
        description: Environment (des, preint, pre, protest, pro)
        required: true
      environment:
        description: Tenant (bk, lf, md, oy, pb, st, ut, za, zh)
        required: true

jobs:
  test-workflow:
    env:
      GITHUB_REPOSITORY: 'extensionlib'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Verify Subjects
        uses: ./packages/validate-schema-action
        with:
          subjects-path: './packages/validate-schema-action/test-data/complex-valid-subjects'
      - name: Publish Subjects
        uses: ./packages/schema-publisher-action
        with:
          subjects-path: './packages/schema-publisher-action/test-data/complex-valid-subjects'
          tenant: '${{ github.event.inputs.tenant }}'
          environment: '${{ github.event.inputs.environment }}'
          dev-access-key: '${{ secrets.DES_LIBDATAX_ACCESSKEY }}'
          dev-secret-key: '${{ secrets.DES_LIBDATAX_SECRETKEY }}'
          preint-access-key: '${{ secrets.PREINT_LIBDATAX_ACCESSKEY }}'
          preint-secret-key: '${{ secrets.PREINT_LIBDATAX_SECRETKEY }}'
          pre-access-key: '${{ secrets.PRE_LIBDATAX_ACCESSKEY }}'
          pre-secret-key: '${{ secrets.PRE_LIBDATAX_SECRETKEY }}'